// Generated by gencpp from file roadmap/ObPixels.msg
// DO NOT EDIT!


#ifndef ROADMAP_MESSAGE_OBPIXELS_H
#define ROADMAP_MESSAGE_OBPIXELS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roadmap
{
template <class ContainerAllocator>
struct ObPixels_
{
  typedef ObPixels_<ContainerAllocator> Type;

  ObPixels_()
    : i_pixels()  {
    }
  ObPixels_(const ContainerAllocator& _alloc)
    : i_pixels(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _i_pixels_type;
  _i_pixels_type i_pixels;





  typedef boost::shared_ptr< ::roadmap::ObPixels_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roadmap::ObPixels_<ContainerAllocator> const> ConstPtr;

}; // struct ObPixels_

typedef ::roadmap::ObPixels_<std::allocator<void> > ObPixels;

typedef boost::shared_ptr< ::roadmap::ObPixels > ObPixelsPtr;
typedef boost::shared_ptr< ::roadmap::ObPixels const> ObPixelsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roadmap::ObPixels_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roadmap::ObPixels_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roadmap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/melodic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roadmap': ['/home/turtlebot/catkin_ws/src/roadmap/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roadmap::ObPixels_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roadmap::ObPixels_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roadmap::ObPixels_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roadmap::ObPixels_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roadmap::ObPixels_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roadmap::ObPixels_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roadmap::ObPixels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7420fa011a5dd82868f361f09461436b";
  }

  static const char* value(const ::roadmap::ObPixels_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7420fa011a5dd828ULL;
  static const uint64_t static_value2 = 0x68f361f09461436bULL;
};

template<class ContainerAllocator>
struct DataType< ::roadmap::ObPixels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roadmap/ObPixels";
  }

  static const char* value(const ::roadmap::ObPixels_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roadmap::ObPixels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Indices of the obstacle pixels\n\
int32[] i_pixels\n\
";
  }

  static const char* value(const ::roadmap::ObPixels_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roadmap::ObPixels_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.i_pixels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObPixels_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roadmap::ObPixels_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roadmap::ObPixels_<ContainerAllocator>& v)
  {
    s << indent << "i_pixels[]" << std::endl;
    for (size_t i = 0; i < v.i_pixels.size(); ++i)
    {
      s << indent << "  i_pixels[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.i_pixels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROADMAP_MESSAGE_OBPIXELS_H
